### ISSUE TITLE
InventoryManager AutoEject option to keep X stacks 

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#1904] opened 2021-02-03 21:03 UTC
When throwing out items and KeepStacks is not set to 0, it'll keep X stacks instead of throwing them.

**Comment by Xiaro** [comment] 2021-02-03 21:06
duplicate of #594

**Comment by l1ving** [comment] 2021-02-03 21:06
I'm stupid

**Closed by Xiaro** 2021-02-03 21:06 UTC
Labels: -duplicate, -module, enhancement
