### ISSUE TITLE
Bug - Screen goes black as soon as the mods all load.

### ISSUE THREAD

**Issue by varrooonn** [kami-blue/client#1473] opened 2020-10-15 13:49 UTC
**Describe the bug**
Screen goes black if I go fullscreen when using kami blue the most recent nightly

**To Reproduce**
1. Click launch from the minecraft launcher
2. after everything loads, press full screen.

**Expected behavior**
it is supposed to not go black

after becoming black, even if you un-fullscreen it, it remains black.

**Screenshots**
(fullscreen)
![image](https://user-images.githubusercontent.com/60920165/96138090-0c4f7680-0f1b-11eb-96c5-7d2c14a1bd8e.png)

(un-fullscreened)
![image](https://user-images.githubusercontent.com/60920165/96138210-25f0be00-0f1b-11eb-9830-906fd365a149.png)

**Additional context**
all the mods used with the recent kami blue version:
Salhack 2.4 release 
BetterFPS - 1.4.8
Osiris+ 3.0
Impact 4.1.9 
ElytraBot 2.1
(forge version : 1.12.2 - Forge 14.23.5.2854)

**Comment by l1ving** [comment] 2020-10-15 13:50
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by varrooonn** [comment] 2020-10-15 13:50
yeah this is the newest kami blue version

**Comment by l1ving** [comment] 2020-10-15 13:51
>  Please provide alternate steps to reproduce it or more information such as a video.

**Comment by varrooonn** [comment] 2020-10-15 13:51
I am

**Comment by l1ving** [comment] 2020-10-15 13:51
You did not.

**Comment by varrooonn** [comment] 2020-10-15 13:51
going to

**Comment by l1ving** [comment] 2020-10-15 15:17
Won't fix, determined on Discord this issue is specific to their computer.

**Closed by l1ving** 2020-10-15 15:17 UTC
Labels: --info-requested, bug

**Comment by slashsynapse** [comment] 2020-10-18 11:44
This is happening again aaaaaaaaaaaaaaaaaaaaaaaa

**Comment by slashsynapse** [comment] 2020-10-18 11:45
its some render issue from the small screen to full screen

**Comment by slashsynapse** [comment] 2020-10-18 11:45
when I make it small screen again, I get it ok, but the game is frozen

**Comment by slashsynapse** [comment] 2020-10-18 11:45
I deleted the whole .minecraft folder and re did *everything*

**Comment by l1ving** [comment] 2020-10-18 11:54
see #1474

**Comment by slashsynapse** [comment] 2020-10-18 12:01
I saw
