### ISSUE TITLE
Map names shown for MapPreview

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/client#1304] opened 2020-09-06 09:17 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't see the names of my maps when I use MapPreview

**Describe the solution you'd like**

Show map names

**Describe alternatives you've considered**

I haven't considered any

**Additional context**

Seems like a bug

**Comment by GoodPro712** [comment] 2020-09-06 09:27
like, the actual name of the item

**Comment by dominikaaaa** [comment] 2020-09-06 12:30
Duplicate of #957

**Closed** 2020-09-06 12:30 UTC
Labels: -duplicate, -module, enhancement

**Comment by GoodPro712** [comment] 2020-09-06 12:40
didnt see that, sorry
