### ISSUE TITLE
Multi Directional running

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#661] opened 2020-04-08 22:39 UTC
**Is your feature request related to a problem? Please describe.**
Add a feature where the client spoofs directions so that when the user is walking and not interacting with any blocks, that they can run backwards and in any direction.

**Describe the solution you'd like**
The client makes the server think the user is facing where they are going, when the user sees where they want.

**Describe alternatives you've considered**
bhop (but this isnt the same)

**Comment by dominikaaaa** [comment] 2020-04-08 22:41
Duplicate of #633, as that's what #633 does

**Closed by dominikaaaa** 2020-04-08 22:41 UTC
Labels: new/module

**Comment by sylaxofficial** [comment] 2020-04-08 22:44
ok
