### ISSUE TITLE
While using elytraflight, an option to turn off, deploy elytra again and turn on, when the server backtracks the player.

### ISSUE THREAD

**Issue by sylaxofficial** [kami-blue/client#656] opened 2020-04-08 22:11 UTC
**Is your feature request related to a problem? Please describe.**
When I use fast elytra (on 9b9t in particular) I can go fast but after a few seconds it stops me from traveling and tps me back again and again until I turn it off. If there was a way to detect this then that would be amazing, for example getting tpd back for no reason.

**Describe the solution you'd like**
A module setting that can detect lagbacks and can redeploy elytra

**Describe alternatives you've considered**
slower speeds -_-

**Additional context**
Happens to me if a: I fly close over a block    b: Randomly while flying for prolonged periods of time

(this is more of an enhancement sorry ;])

**Comment by dominikaaaa** [comment] 2020-04-08 22:37
Duplicate of #616

**Closed by dominikaaaa** 2020-04-08 22:37 UTC
Labels: new/module
