### ISSUE TITLE
The schamatica work pause when i get into freecam

### ISSUE THREAD

**Issue by Natan515** [kami-blue/client#1467] opened 2020-10-11 14:40 UTC
**Describe the bug**
please please I'm trying!  So when you build a schematic on 1.12.2 java edition, forge, java 8, I have 12 mods and they are: 
ghostwriter, ambient sounds, elytrabot, f5fix, journeymap, kamiblue 1..1.7-45ccdd3f-release.jar, the 2 schematic, cape mod, optifine, world edit, world dowlaod.  So when i use the freecam the schamatic pause, and when i turn off freecam it keeps working, so it make life more anoying, would like it to get fix and i will be able to use freecam while im working on a schamatic... thank u,

**To Reproduce**

1. Go to '... idk use schamatic'
2. Click on '... not sure,,,, schamtic....'
3. Scroll down to '.... schamatic.. .not sure'
4. See error, the baritone stop building the scamatic.

**Expected behavior**

that when i go to freecam it will keep working

**Screenshots**

don't have cus i cant see my own guy on freecam lol

**Additional context**

don't have pls don't remove my bug report i don't get what u want...

**Comment by l1ving** [comment] 2020-10-11 14:40
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by natan515** [comment] 2020-10-11 14:41
I am! it is.

**Comment by natan515** [comment] 2020-10-11 14:43
and again I can't see my dude so how can I record a video?

**Comment by l1ving** [comment] 2020-10-11 14:47
Use a screen recording software or something. OBS / Bandicam on Windows, simplescreenrecorder on *nix

**Comment by l1ving** [comment] 2020-10-11 14:49
> i cant see my own guy on freecam lol

what version are you using?

**Comment by l1ving** [comment] 2020-10-11 14:50
> i will be able to use freecam while im working on a schamatic... thank u,

works fine for other people. 

https://cdn.discordapp.com/attachments/634012886930423818/764632009259221012/Building_In_Freecam.mp4

Send a screenshot of your freecam settings as well as a video of the problem

**Comment by natan515** [comment] 2020-10-11 15:04
no, i do know how to film i jutt say my charecter "natan515" isnt there in freecam cus of a bug

**Comment by natan515** [comment] 2020-10-11 15:05
and it's from a sing player and i don't think the last version.

**Comment by l1ving** [comment] 2020-10-11 15:05
> works fine for other people.

> Send a screenshot of your freecam settings as well as a video of the problem

**Comment by natan515** [comment] 2020-10-23 19:26
nvm it works now u can close it.

**Comment by natan515** [comment] 2020-10-23 19:45
no,
![2020-10-23_22 43 03](https://user-images.githubusercontent.com/66911017/97047197-40f9a880-1581-11eb-9ded-713ea79a16c1.png)
 it keeps not working... want my log info?  it just like follow my mouse still when I'm at freecam so it just pause and it doesn't tell me it pause and when i disable freecam it just keeps like normal.. im super confused.

**Comment by l1ving** [comment] 2020-10-23 19:46
I need a video and a screenshot of `;tsc`

**Comment by natan515** [comment] 2020-10-23 19:52
https://youtu.be/THi9Ur8axpE, 
![2020-10-23_22 51 32](https://user-images.githubusercontent.com/66911017/97047934-5b805180-1582-11eb-89e4-05f723c6d97b.png)
![2020-10-23_22 51 36](https://user-images.githubusercontent.com/66911017/97047952-5fac6f00-1582-11eb-857a-f882adb7c7fa.png)
![2020-10-23_22 51 38](https://user-images.githubusercontent.com/66911017/97047959-620ec900-1582-11eb-941f-009dd6da1aec.png)

**Comment by l1ving** [comment] 2020-10-23 20:17
Send a screenshot of your freecam settings

**Comment by natan515** [comment] 2020-10-23 20:38
![2020-10-23_23 37 28](https://user-images.githubusercontent.com/66911017/97051939-cb91d600-1588-11eb-82d7-753932e794b3.png)

**Comment by l1ving** [comment] 2020-10-24 12:13
#1506 has more info

**Comment by natan515** [comment] 2020-10-24 12:59
but he just says it's not the same issue.

**Comment by l1ving** [comment] 2020-10-24 13:01
Oh I can't read. My b

**Comment by natan515** [comment] 2020-11-05 21:37
It's only happening when I have the mod of arrow key move on.

**Comment by l1ving** [comment] 2021-01-07 13:17
Is this issue still happening? Don't close it for no reason

**Comment by Natan515** [comment] 2021-01-07 13:22
It doesn't

**Closed** 2021-01-07 13:31 UTC
Labels: -incompatible, -module
