### ISSUE TITLE
Jar installer

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#271] opened 2019-12-08 20:32 UTC
Because people don't read the readme for some reason

**Comment by zeroeightysix** [comment] 2019-12-08 21:22
Why not have an actual installer instead of install instructions?

**Comment by S-B99** [comment] 2019-12-08 21:24
That's a better idea honestly.

**Comment by d1gress** [comment] 2019-12-16 13:56
the only way i can think of doing this is using git to download the source, build it with jdk, then send the last modified file in /libs/builds with "release" in its name to the mods folder but im stupid so i probably overcomplicated about 193 things

**Comment by S-B99** [comment] 2019-12-16 14:06
No, it can literally copy forges updater.

I added it in release v1.1.1 but making a separate program to automatically get the url and download it is what the issue is for

**Comment by S-B99** [comment] 2020-04-03 19:52
Currently there's an installer branch which demonstrates how to keep it a forge mod but also have the jar do something when opened. I doubt I'll ever get around to it, so I'm probably going to close this as won't fix. I'll comment the important code here before I delete the branch.

**Comment by S-B99** [comment] 2020-04-03 19:55
Alright, so it all goes in `build.gradle`.

Move your buildscript to the top, as this requires it. 

After build: dependson(shadowjar) add this

```java
void application() {
    mainClassName = 'wtf.bella.installer.Main'
} 
```

And you can make that class do something

```java
package wtf.bella.installer;

public class Main {
    public static void main(String[] args) {
        System.out.println("ran installer!!!");
    }
}
```

**Comment by cookiedragon234** [comment] 2020-04-03 21:40
😯

**Comment by humboldt123** [comment] 2020-07-12 20:21
now this is podracing

**Comment by humboldt123** [comment] 2020-07-12 23:36
Alrighty. I'm *thinking* of doing this in Python.

**Comment by dominikaaaa** [comment] 2020-07-12 23:42
why the fuck.

**Closed** 2020-07-15 14:23 UTC
Labels: 00-help-wanted, 04-building, good-first-issue, new/module

**Comment by dominikaaaa** [comment] 2020-07-15 14:25
![image](https://user-images.githubusercontent.com/17222512/87557069-77bc4a80-c685-11ea-9599-bbf702a55b65.png)
Kinda pog

Automatically deletes older versions of KAMI and KAMI Blue on confirmation and warns if you don't have Forge installed
