### ISSUE TITLE
InventoryViewer third person view bug

### ISSUE THREAD

**Issue by DisNin** [kami-blue/client#1361] opened 2020-09-24 12:41 UTC
**Describe the bug**
InventoryViewer go brrrrr in F5

**To Reproduce**
1. Go to 'Minecraft world'
2. Click on 'Y'
3. Scroll down to 'InventoryViewer'
4. Enable it
5. Switch to F5
6. See cool inventoryViewer

**Screenshots**
![based](https://user-images.githubusercontent.com/68169685/94146268-5db89880-fe7c-11ea-89d8-964f87d01a73.png)

**Comment by dominikaaaa** [comment] 2020-09-24 12:47
Duplicate of #1197, but I'm leaving this open as that one wasn't reported properly.

**Comment by DisNin** [comment] 2020-09-24 12:48
ok, there are already several updates like this, I will try to remove salhack, usually it is salhack problem

**Closed** 2020-10-20 01:05 UTC
Labels: -module, bug
