### ISSUE TITLE
The gui can go off screen

### ISSUE THREAD

**Issue by sedfg** [kami-blue/client#1767] opened 2020-12-26 14:04 UTC
<img width="279" alt="Screen Shot 2020-12-27 at 12 58 28 am" src="https://user-images.githubusercontent.com/38718075/103152700-aa46a380-47de-11eb-837f-60692940d278.png">

**Describe the bug**

Some of the menus get pretty hard to see because the become off screen. This means that I cant have any part of the gui on the far right part of my screen as when I try to edit the settings of a mod they will appear of screen.

**To Reproduce**

1. Put one of the subcategories -eg movement- on the far right of the screen (but so you can still see it)
2. Right click on one of the modules. The settings for this module will appear, at least in part, off the screen.

**Expected behavior**
The drop own list will appear to the left (in a visible area)

**Debug info**

**Additional context / media**

plz dont say that this is working as intended

**Comment by l1ving** [comment] 2020-12-26 14:05
Working as intended. Won't fix, this doesn't happen in the new gui.

**Comment by sedfg** [comment] 2020-12-26 14:06
new gui = when?

**Closed by l1ving** 2020-12-26 14:05 UTC
Labels: -module, bug

**Comment by Cisaa** [comment] 2020-12-26 14:06
i hope fucking soon

**Comment by l1ving** [comment] 2020-12-26 14:07
#790 / #1510
