### ISSUE TITLE
Holefill

### ISSUE THREAD

**Issue by ub3rshadow** [kami-blue/client#1532] opened 2020-10-29 23:27 UTC
A module that automatically fills obsidian and bedrock holes with obsidian within a set range to stop other players from using them. Options would be a slider for range, raytracing to the hole, whether it should legitimately switch to obsidian and whether it should place while the user is moving.

**Comment by Xiaro** [comment] 2020-10-30 02:24
Duplicate of #1223

**Closed by Xiaro** 2020-10-30 02:24 UTC
Labels: --plugin, -duplicate, -module, new
