### ISSUE TITLE
Announcer module?

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#868] opened 2020-05-24 00:11 UTC
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Sending message automatically in the chat like "I just eat ......", "I just walked.....", "I just walked....."

**Describe alternatives you've considered**
Adding it as part of the spammer, you can choose between spamming texts in spammer.txt and announcer message, or sending them together.

**Additional context**
![image](https://user-images.githubusercontent.com/62033805/82742904-9c550f80-9d31-11ea-9be0-bf4f6dcbd123.png)

**Comment by dominikaaaa** [comment] 2020-05-24 00:13
Duplicate of #684

**Closed** 2020-05-24 00:13 UTC
Labels: 99-duplicate, new/module
