### ISSUE TITLE
BreakingWarning and LagNotifier are incompatible with forgehax and future 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#647] opened 2020-04-04 13:08 UTC
It causes rendering issues such as this 

![](https://cdn.discordapp.com/attachments/666652020601782293/697875546784399512/2020-04-09_20.27.43.png)

this may be due to the blending

**Comment by dominikaaaa** [comment] 2020-08-29 02:56
Would https://github.com/kami-blue/client/commit/578bbda083ea2b6c26e1196fba5db381b913ec60 have fixed this @Xiaro?

**Comment by Xiaro** [comment] 2020-08-29 03:07
> Would [578bbda](https://github.com/kami-blue/client/commit/578bbda083ea2b6c26e1196fba5db381b913ec60) have fixed this @Xiaro?
Texture 2D issue, was caused by Kami's font renderer. Now LagNotifier doesn't use it anymore so it should be fixed.

**Closed by Xiaro** 2020-08-29 03:07 UTC
Labels: -incompatible, -module, bug
