### ISSUE TITLE
FakePlayer

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#741] opened 2020-04-22 16:23 UTC
**Requested feature**
FakePlayer

**How should it work**
Create a fake player with different name and UUID (if possible) for testing combat & esp modules, etc

**Comment by dominikaaaa** [comment] 2020-04-22 16:30
Duplicate of #198

**Comment by dominikaaaa** [comment] 2020-04-22 16:30
It's a cool idea but not that easy to do.

**Comment by pNoName1337** [comment] 2020-04-22 16:31
So will it bee added in the future?

**Comment by dominikaaaa** [comment] 2020-04-22 16:32
No, I closed the original issue as won't fix.

**Comment by dominikaaaa** [comment] 2020-04-29 16:32
Nvm working on it lol

**Comment by dominikaaaa** [comment] 2020-05-03 17:51
I made my own and played around with Heph's, unfortunately neither of them can get an actual interactable player working (ie hitting and stuff does nothing) but it would be cool to be able to right click someone and make a fake model, so I will be doing that.

**Comment by cookiedragon234** [comment] 2020-05-03 19:04
Wdym they can’t be interacted? If you post/tm what you wrote so far I can give you help...

**Comment by dominikaaaa** [comment] 2020-05-03 19:06
I'll put it in a branch when the charger for my laptop arrives from Amazon, as currently it's charger is broken

**Comment by pNoName1337** [comment] 2020-05-03 19:53
I have some ideas for this module
1) Add command `;fakeplayer` and `;fakeplayer create 'name' 'x' 'y' 'z'` and `;fakeplayer delete 'name'` to create & delete fake players (with custom name and xyz position), also create fakeplayer on your position if u didnt type coords (ex: `;fakeplayer Hausemaster`)
2) Add option to the menu (render/misc tab) to enable/disable fake players
3) Make fake players get skin of their name (ex: fakeplayer with name 'popbob' will have popbob's skin)

**Comment by dominikaaaa** [comment] 2020-05-03 19:54
I already wrote the code for that. You can entire custom UUIDs or right click a player to get their UUID when it's enabled.

**Comment by dominikaaaa** [comment] 2020-05-03 19:55
The only thing left to do is put it on a branch so cooker can help me out with getting it to actually be hittable

**Closed** 2020-09-19 20:42 UTC
Labels: -module, new
