### ISSUE TITLE
AutoWalk direction is null 

### ISSUE THREAD

**Issue by Nowilltolife** [kami-blue/client#1014] opened 2020-07-05 00:38 UTC
**Describe the bug**
Client crash when Baritone "thisway" command and AutoWalk forward are enabled

**To Reproduce**
1. Look in any direction and execute this way command with any given length
2. Enable AutoWalk
3 See crash

**Expected behavior**
Baritone should path and autowalk should work

**Comment by dominikaaaa** [comment] 2020-07-05 00:40
Provide a log.

**Comment by Nowilltolife** [comment] 2020-07-05 00:46
this is the minecraft crash report: https://pastebin.com/P0uvNGbg

**Comment by dominikaaaa** [comment] 2020-07-05 00:48
So the issue is that baritone says the current process isn't null, but the direction is, causing a crash because it's asserting non null.

Tbh none of that code should be asserting non null, let alone be null like **ever**

**Comment by iBuyMountainDew** [comment] 2020-07-31 20:33
Fixed in ff9cb1f0dcda78d6c977e7bb6696afaff8d8fd65 and da5719640e75cce1182406dc6ca831e998aa04fb.

**Closed by iBuyMountainDew** 2020-07-31 20:33 UTC
Labels: bug/module
