### ISSUE TITLE
Quiver/auto self bow

### ISSUE THREAD

**Issue by alexanderfou** [kami-blue/client#1337] opened 2020-09-16 17:15 UTC
Idea: A new combat module that when toggled shoots arrows with positive effects into the air like speed, strength, etc and then toggles off

How to make it work:
I don't know how to do this programmatically, but it would be something like spoof a rotation straight upwards, move the arrow to the 1st (upper left) slot in the inventory, and shoot the arrow into the air to hit urself. If there are multiple arrows like speed and strength, it can check for certain types of arrows and then rotate them through the 1st slot.

**Comment by dominikaaaa** [comment] 2020-09-16 17:16
Duplicate of #1264 and #970

**Closed** 2020-09-16 17:15 UTC
Labels: -module, new
