### ISSUE TITLE
Better movement hacks over bedrock when pvping.

### ISSUE THREAD

**Issue by Enrott** [kami-blue/client#852] opened 2020-05-17 08:36 UTC
**Is your feature request related to a problem? Please describe.**
Lack of player speed hacks for 2b2t pvp, I'm stuck with sprint to run fast. and timer speed not very good for this especially on bedrock floor.

**Describe the solution you'd like**
An ability to run around bedrock faster. Most clients have a 'bunnyhop' module which allows for running backwards over bedrock and is a little faster than sprint jumping due to its 'strafe' qualities.

**Describe alternatives you've considered**
Definitely Step. The instant step i believe can bypass hunger since its not really 'jumping'.

**Additional context**
**Bhop** I know most clients 'bhop' is bugged on 2b2t, so maybe slightly nerfed? I think Osiris client made a decent bhop. I never used Osiris much.
**Step** Step works on Impact using ncp mode but 2b2t's anti cheat bugs going over fences. Probably by default make it only 1 block height as fences causes rubber-banding. You could even use step with the 'timer speed' module. Would that work over bedrock? I don't know, but worth a try?

**Comment by zisis912** [comment] 2020-05-17 10:42
you could have scaffold hacks and walk on the highest bedrock level (y5)

**Comment by Enrott** [comment] 2020-05-17 10:45
> you could have scaffold hacks and walk on the highest bedrock level (y5)

good for temporary but would take up extra room in taskbar for blocks which i would rather keep stuff like obsidian for trapping.

**Comment by dominikaaaa** [comment] 2020-05-17 12:30
Bhop is #180, which I closed as won't fix.

**Comment by dominikaaaa** [comment] 2020-05-17 12:31
#633 is strafe btw

**Comment by Enrott** [comment] 2020-05-18 14:30
Any chance of adding Step or no? Also would Strafe allow backwards running? Sprint wont allow you to run backwards.

**Comment by dominikaaaa** [comment] 2020-05-18 14:30
Step is already added

**Comment by dominikaaaa** [comment] 2020-05-18 14:31
Strafe is planned

**Comment by Enrott** [comment] 2020-05-18 14:31
really? i gotta look harder under movement right?

**Comment by dominikaaaa** [comment] 2020-05-18 14:31
it's in a branch

**Comment by mothheart** [comment] 2020-06-08 01:23
Would you mind if I ported Wurst's speedhacks to Kami?

**Comment by dominikaaaa** [comment] 2020-06-08 01:40
As long as wurst is under a compatible license and you include the original license in the code, you're free to pr it.

**Comment by mothheart** [comment] 2020-06-08 01:42
I'll get to work tomorrow then. Wurst's license is GPLv3, same as Kami. There should be no problem

**Comment by dominikaaaa** [comment] 2020-06-08 01:43
KAMI is under LGPLv3, and GPLv3 cannot be sublicensed under LGPLv3. However, if you get explicit permission, it should be fine.

**Comment by mothheart** [comment] 2020-06-08 01:44
Oh yikes. I'll get in touch with the wurst guys, sorry for the mixup.

**Comment by dominikaaaa** [comment] 2020-07-31 20:54
I'm closing this as duplicate of #180 (won't fix), #354 (added) and #633

**Closed by dominikaaaa** 2020-07-31 20:54 UTC
Labels: 00-low-priority, 99-duplicate, new/module
