### ISSUE TITLE
Causes computer to emit RF

### ISSUE THREAD

**Issue by charlie353535** [kami-blue/client#2105] opened 2021-03-05 17:29 UTC
**Describe the bug**
GPU emits an RF signal that is picked up on my sound system as a 1.5khz signal (400-500mv p/p)

**To Reproduce**
Open the GUI

**Expected behavior**
Radio signals not being emitted

**Debug info**
![image](https://user-images.githubusercontent.com/32582243/110151267-30cbc280-7dd8-11eb-981b-a9e8ac9772d1.png)

**Additional context / media**
Uh the amplifier is a Pioneer SA420

**Comment by Xiaro** [comment] 2021-03-05 17:32
Very technical issue

**Comment by lukflug** [comment] 2021-03-05 17:33
maybe the GUI is haunted?

**Comment by l1ving** [comment] 2021-03-05 17:33
what the fuck

**Comment by L-Nadav** [comment] 2021-03-05 17:35
top teir

**Comment by l1ving** [comment] 2021-03-05 17:35
Am I wrong in saying this seems normal with lots of GL calls being made? https://forum.level1techs.com/t/electro-magnetic-interference-from-gpu/97509

**Comment by gerald0mc** [comment] 2021-03-05 17:36
hm maybe try checking to see if your cpu is degrading take it out and if there are any gold looking pins on the bottom scrape them off they are your cpu degrading and you have to regularly scrape it off that is causing the rf signal

**Comment by NirvanaNevermind** [comment] 2021-03-05 17:39
https://www.zdnet.com/article/academics-turn-ram-into-wifi-cards-to-steal-data-from-air-gapped-systems/
https://arxiv.org/abs/1411.0237

Based off this article and the paper by cornell university, i believe kami blue is stealing user data over RF.

**Comment by l1ving** [comment] 2021-03-05 17:44
Closing this for trolling until someone can give me definite evidence this isn't normal for GPU (relatively) intensive programs. 

Also neither me nor (probably) any of the active contributors have the equipment to debug such a thing, let alone write code to steal information in such a long winded and obscure way. 

All the code is public and builds are reproducible with the only changes between your machine and my build system being the version number, as you can easily see in a program such as jardiff.

**Closed by l1ving** 2021-03-05 17:44 UTC
Labels: --info-requested, -help-wanted

**Comment by charlie353535** [comment] 2021-03-05 17:52
https://cdn.discordapp.com/attachments/812053017280512071/817446642861080586/VID_20210305_172049.mp4
that's the noise kami blue GUI makes when used.

**Comment by charlie353535** [comment] 2021-03-05 17:58
> hm maybe try checking to see if your cpu is degrading take it out and if there are any gold looking pins on the bottom scrape them off they are your cpu degrading and you have to regularly scrape it off that is causing the rf signal

both CPU's are totally clean. as is memory.

**Comment by JohnShiozo** [comment] 2021-03-05 18:14
lmfao

**Comment by iBuyMountainDew** [comment] 2021-03-05 18:18
lol wtf is this

**Comment by 0x150** [comment] 2021-03-05 21:37
that is definitely not normal

**Comment by 0x150** [comment] 2021-03-05 21:40
Checked a bit, noticed the same thing happening for me. seems to be an opengl thing when opengl uses the gpu to render, same noise, but higher pitched for me. Same happens with blender renders (at least fast ones).

Conclusion: Common thing, but different noise across gpus. Opengl "issue"

**Comment by l1ving** [comment] 2021-03-05 21:41
> Am I wrong in saying this seems normal with lots of GL calls being made? [forum.level1techs.com/t/electro-magnetic-interference-from-gpu/97509](https://forum.level1techs.com/t/electro-magnetic-interference-from-gpu/97509)

Hence
