### ISSUE TITLE
Enchantment Glint

### ISSUE THREAD

**Issue by iBuyMountainDew** [kami-blue/client#1762] opened 2020-12-25 13:47 UTC
Idea from closed ticket (660211984389636129 - BushQuotient at time of writing).

A module to customize the enchantment glint how you like, making it rainbow, adding a color hue, or not rendering it at all. Things of that sort.

https://i.imgur.com/jn80ykH.png

**Comment by Xiaro** [comment] 2020-12-27 18:31
Duplicate of #1084

**Closed by Xiaro** 2020-12-27 18:31 UTC
Labels: --plugin, -duplicate, -module
