### ISSUE TITLE
FriendHighlight breaks clicking links in chat

### ISSUE THREAD

**Issue by xfinate** [kami-blue/client#963] opened 2020-06-21 01:45 UTC
I have been unable to use chat links for awhile now. It affects anything in the chat that you can clink on such as web links, buttons, etc. I have tried the basics to solve the problem and the only solution I found was to take kami blue out of my mods folder. 

If you want to create the problem just put the latest kami blue into your mods folder and launch up a single player world, paste a link on the chat and try to click on it.

I attached a picture of what is supposed to happen when clicking on links.
https://imgur.com/a/usRanV6

**Comment by dominikaaaa** [comment] 2020-06-21 01:47
Please include ;tsc, as I asked you to on discord

**Comment by xfinate** [comment] 2020-06-21 01:56
![image](https://user-images.githubusercontent.com/65992583/85215025-d15c7e00-b340-11ea-9ee3-84a30f25025d.png)

**Comment by xfinate** [comment] 2020-06-21 01:56
![image](https://user-images.githubusercontent.com/65992583/85215042-f4872d80-b340-11ea-9169-02c7cb453758.png)

**Comment by Xiaro** [comment] 2020-06-21 19:23
That is a bug of friendhighlight, links should work after you turn it off

**Comment by dominikaaaa** [comment] 2020-06-21 19:24
That's probably caused by friendhighlight regex replacing friends names in chat

**Comment by xfinate** [comment] 2020-06-21 19:29
thanks, and yes turning off friend highlight fixed the problem :)

**Comment by l1ving** [comment] 2020-12-29 20:38
I can't actually figure out what MC is doing to make links clickable, but it appears that modifying the message packet at all breaks it

**Comment by l1ving** [comment] 2021-01-05 01:49
I'm closing this as won't fix. Not that necessary of a feature, and I still don't know how MC does it.

**Closed by l1ving** 2021-01-05 01:49 UTC
Labels: -module, bug
