### ISSUE TITLE
Tree Aura (TreePlace)

### ISSUE THREAD

**Issue by xTMMDx** [kami-blue/client#764] opened 2020-04-28 21:42 UTC
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
TreeAura puts a block of land or does not put, depending on the settings, and plant trees on them when you go, it would be nice to adjust the planting frequency and tree size (1 or 4 saplings).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by dominikaaaa** [comment] 2020-04-28 22:38
Why would this be a useful feature?

**Comment by dominikaaaa** [comment] 2020-04-28 22:39
And isn't this a duplicate of #224?

**Comment by xTMMDx** [comment] 2020-04-29 08:38
I did not know that it was a duplicate. I think that it will help #TeamTrees and those people who just want to plant trees on spawn. Maybe someday it will be useful to someone not for planting trees on spawn, for example, at their base. After all, KAMI has a function that spawns Withers, why not make a function with trees too?

**Comment by dominikaaaa** [comment] 2020-04-29 13:16
Because Withers take more then a second to place by hand and are common on anarchy servers. I don't exactly see normal players spamming saplings. 

If you want to automatically farm trees you can use baritone.

**Closed by dominikaaaa** 2020-04-29 13:16 UTC
Labels: new/module
