### ISSUE TITLE
Add chest in minecart to stashfinder

### ISSUE THREAD

**Issue by AssasinsGinger** [kami-blue/client#951] opened 2020-06-17 01:17 UTC
**Is your feature request related to a problem? Please describe.**
Chests in minecarts is a thing to save a stash, as it doesn't ping you as it would to regular chests. Causing potential stashes to not be seen.

**Describe the solution you'd like**
Add chest in minecart an option to ping you.

**Describe alternatives you've considered**
I don't know if this is easy to make, so I don't really have alternatives

**Additional context**
Stashfinder pings you if there's multiple chests nearby, do the same thing if it encounters chests in minecarts.

**Comment by dominikaaaa** [comment] 2020-06-17 01:39
Duplicate of #831

**Closed** 2020-06-17 01:39 UTC
Labels: 99-duplicate, enhancement/module
