### ISSUE TITLE
Account Manager

### ISSUE THREAD

**Issue by AddMulesToAutoRemount** [kami-blue/client#936] opened 2020-06-08 02:11 UTC
I know this probably would be a pain to code, or maybe impossible to do at all;
An account manager, a place (probably in the main menu) where you can change your account/re-login to your account without having to reload your game and launcher. A lot of other utility mods have this feature, and I would like to see it in kami blue.

**Comment by dominikaaaa** [comment] 2020-06-08 02:25
Duplicate of #12

**Closed by dominikaaaa** 2020-06-08 02:25 UTC
Labels: new/module
