### ISSUE TITLE
Offhandgap totem bug

### ISSUE THREAD

**Issue by v4ne4ka** [kami-blue/client#777] opened 2020-05-03 18:51 UTC
**Describe the bug**
If i open inventory while eating gapples, i hold a totem in my mouse so if i close the inventory the totem drops

**To Reproduce**
1. Turn on "offhandgap" module
2. Start eating gapples
3. Press E while eating gapples

**Expected behavior**
I expected totem on gapples' place or in left hand, not in my mouse

**Screenshots**
Everything is in the video

**Additional context**
https://youtu.be/q01DF-If1X8 (0:32)

**Comment by dominikaaaa** [comment] 2020-05-05 16:43
This is caused by my quick fix for a crash that happens when you open a non inventory gui while gapping (see file history)

**Comment by dominikaaaa** [comment] 2020-05-06 23:55
Fix for this: revert my last changes and instead return when inside GUI instead of whatever the hell I'm doing now

**Comment by dominikaaaa** [comment] 2020-05-07 02:01
Actually, I was already doing that. I have no idea how I would fix it. 

It's because of this
```java
	private void moveGapsWaitForNoGui() {
		if (isGuiOpened) return;
		moveGapsToInventory(gaps);
	}
```
which is used as a workaround for an out of bounds crash if you finish eating while looking at a chest, which is caused by the slot to move it back to not existing, as chests change what number means which slot. 

I'm closing as won't fix until there's a better solution.

**Closed by dominikaaaa** 2020-05-07 02:01 UTC
Labels: bug/module
