### ISSUE TITLE
latest version crashes on loading

### ISSUE THREAD

**Issue by charlesathon** [kami-blue/client#1479] opened 2020-10-19 09:01 UTC
**Describe the bug**
Crashed on loading

**To Reproduce**
I installed the latest version into my mods folder
deleted everything else so that it was only kamiblue in there
booted forge 1.12.2
and the game crashed on loading.

**Expected behavior**
Kami to load

**Screenshots**

**Additional context**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-1.1.7-8963cd39-release.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/19/20 9:56 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue
 (kamiblue)
Caused by: java.lang.ExceptionInInitializerError
	at me.zeroeightsix.kami.module.modules.misc.AntiAFK.onEnable(AntiAFK.kt:84)
	at me.zeroeightsix.kami.module.Module.enable(Module.kt:100)
	at me.zeroeightsix.kami.KamiMod.init(KamiMod.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at baritone.api.Settings.<init>(Unknown Source)
	at baritone.api.BaritoneAPI.<clinit>(Unknown Source)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 538313176 bytes (513 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version         | Source                              | Signature                                |
	|:----- |:--------- |:--------------- |:----------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2          | minecraft.jar                       | None                                     |
	| LCHI  | mcp       | 9.42            | minecraft.jar                       | None                                     |
	| LCHI  | FML       | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | kamiblue  | v1.1.7-8963cd39 | kamiblue-1.1.7-8963cd39-release.jar | None                                     |

	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-1.1.7-8963cd39-release.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GT 1030/PCIe/SSE2'

**Comment by l1ving** [comment] 2020-10-19 11:09
Disable AntiAfk. Duplicate of #1463

**Closed by l1ving** 2020-10-19 11:10 UTC
Labels: -module, bug

**Comment by charlesathon** [comment] 2020-10-19 11:49
Thanks for your help.

How can I disable antiafk if I can't load the game?

**Comment by l1ving** [comment] 2020-10-19 11:49
Edit your config file manually. Search a AntiAFK and set enabled to false

**Comment by charlesathon** [comment] 2020-10-19 18:08
Thanks

**Comment by charlesathon** [comment] 2020-10-19 18:12
In the KAMIBlueLastConfig txt file it just contains the text:
KAMIBlueConfig.json and I can't open the .json file as I don't have
anything to open it with

Which config file do you mean?

**Comment by l1ving** [comment] 2020-10-19 18:12
> Which config file do you mean?
KAMIBlueConfig.json

**Comment by charlesathon** [comment] 2020-10-19 18:36
Thank you. How would you recommend editing this .json file?

**Comment by l1ving** [comment] 2020-10-19 18:36
With the same program you used to open KAMIBlueLastConfig

**Comment by charlesathon** [comment] 2020-10-19 19:21
Thank you so much for enduring my idiocy. Great client. Much appreciated

**Comment by l1ving** [comment] 2020-10-19 19:22
It'll be fixed next release, happy to help
