### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by pNoName1337** [kami-blue/client#742] opened 2020-04-22 17:30 UTC
KAMI Blue is crashing on start
Error: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kotlin/TypeCastException
Game logs: [logs.zip](https://github.com/kami-blue/client/files/4517968/logs.zip)

**Comment by iBuyMountainDew** [comment] 2020-04-22 17:32
It's a bug with the gradle build, I'd assume it's because the Kotlin standard library is not being brought into the shadow jar. @dominikaaaa what's your take?

**Comment by dominikaaaa** [comment] 2020-04-22 17:43
Um that's probably it. I didn't test outside a dev env.

**Comment by pNoName1337** [comment] 2020-04-22 17:46
This error again
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kotlin/TypeCastException

**Comment by dominikaaaa** [comment] 2020-04-22 17:46
What's the full version number?

**Comment by pNoName1337** [comment] 2020-04-22 17:46
bebc4e9

**Comment by pNoName1337** [comment] 2020-04-22 17:47
[logs.zip](https://github.com/kami-blue/client/files/4518071/logs.zip)
game logs if needed

**Comment by pNoName1337** [comment] 2020-04-22 17:49
also crash log
`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (kamiblue-1.1.4-bebc4e9-release.jar)
  ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/22/20 8:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(rj:467)
	at net.minecraft.client.Minecraft.func_99999_d(rj:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1930220448 bytes (1840 MB) / 2382364672 bytes (2272 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F2_pre1 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version        | Source                                        | Signature                                |
	|:----- |:------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft           | 1.12.2         | minecraft.jar                                 | None                                     |
	| LC    | mcp                 | 9.42           | minecraft.jar                                 | None                                     |
	| LC    | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LC    | forge               | 14.23.5.2847   | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LC    | ichunutil           | 7.2.1          | iChunUtil-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | backtools           | 7.0.0          | BackTools-1.12.2-7.0.0.jar                    | None                                     |
	| LC    | codechickenlib      | 3.2.2.353      | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | forgehax            | 2.9.0          | forgehax-1.12.2-2.9.0.jar                     | None                                     |
	| LC    | waila               | 1.8.26         | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LC    | infinity            | 0.13.5         | Infinity-0.13.5.jar                           | None                                     |
	| LC    | jei                 | 4.15.0.278     | jei_1.12.2-4.15.0.278.jar                     | None                                     |
	| LE    | kamiblue            | v1.1.4-bebc4e9 | kamiblue-1.1.4-bebc4e9-release.jar            | None                                     |
	| L     | mapwriter           | 2.8.2          | MapWriter-1.12.2-2.8.2.jar                    | None                                     |
	| L     | nei                 | 2.4.2          | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | None                                     |
	| L     | wailaharvestability | 1.1.12         | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (kamiblue-1.1.4-bebc4e9-release.jar)
  
ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
  com.matt.forgehax.asm.ForgeHaxTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F2_pre1
	OptiFine Build: 20190727-121506
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
`

**Comment by pNoName1337** [comment] 2020-04-22 17:57
Same with 749ded4
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: kotlin/TypeCastException

**Comment by dominikaaaa** [comment] 2020-04-22 18:05
I can reproduce it, give me a bit.

**Comment by dominikaaaa** [comment] 2020-04-23 14:26
Closing as this has been reverted in the `master` branch.

**Closed by dominikaaaa** 2020-04-23 14:26 UTC
Labels: bug/module
