### ISSUE TITLE
Rare crash with KamiGuiChat

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/client#1348] opened 2020-09-19 17:51 UTC
**Describe the bug**
Time: 9/19/20 1:13 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at me.zeroeightsix.kami.gui.mc.KamiGuiChat.calculateCommand(KamiGuiChat.java:133)
	at me.zeroeightsix.kami.gui.mc.KamiGuiChat.<init>(KamiGuiChat.java:31)
	at net.minecraft.client.gui.GuiChat.handler$returnKeyTyped$zzp000(GuiChat.java:537)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:134)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:639)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:587)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1886)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1188)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:118)

**To Reproduce**
1. Open the the KAMI Blue command chat
2. Type something

**Additional context**
It doesn't have to be taken as high priority issue since it is a very rare crash. Just a record of it happened. If more crashes happen then we should consider taking this seriously.

**Comment by dominikaaaa** [comment] 2020-09-19 18:02
I've literally never seen this crash before. Commands are all executed in a try catch so this would have to be caused by something else

**Comment by l1ving** [comment] 2020-12-05 19:54
This should be fixed by #1280

**Closed** 2020-12-27 19:23 UTC
Labels: -gui, -low-priority, -wontfix, bug
